[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
#family = "ComicCodeLigatures Nerd Font Mono"
#family = "JetBrainsMono Nerd Font Mono"
#family = "OperatorMono Nerd Font Mono"
#family = "Monofur Nerd Font Mono"
family = "MonoLisa"
style = "Regular"

[font.bold]
family = "MonoLisa"
style = "Bold"

[font.italic]
family = "MonoLisa"
style = "Italic"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
#opacity = 0.9
